# -*- coding: utf-8 -*-
"""al rnn 22/04.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bxiQ4fHzSyl5utla5wMrOUM2MAbfnlLf
"""

import numpy as np
import matplotlib.pyplot as plt
import math
import os
from tqdm import trange

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch import optim

import torch
import torch.nn as nn
from torch.nn.init import uniform_
import torch.nn.functional as F
from torch import optim

from dataset import TimeSeriesDataset
from linear_region_functions import *
import linear_region_functions as lrf
#from metrics import state_space_divergence_binning, power_spectrum_error

from matplotlib.colors import Normalize
from collections import Counter
import seaborn as sns
import copy

X_train = np.load("lorenz63_train.npy").astype(np.float32)[500:]
X_test = np.load("lorenz63_test.npy").astype(np.float32)[500:]
T_train, N = X_train.shape
T_test = X_test.shape[0]

def random_orthogonal_matrix(d, seed=None):
    rng = np.random.default_rng(seed)
    A = rng.standard_normal((d, d))
    Q, R = np.linalg.qr(A)

    signs = np.sign(np.diag(R))
    signs[signs == 0] = 1.0
    Q = Q * signs

    return Q.astype(np.float32)


def apply_rotation(X, Q):
    # X shape: (T, d)
    # row-wise data, so use Q^T on the right
    return (X @ Q.T).astype(np.float32)

import torch.nn.utils.parametrizations as P
import torch.nn.functional as F
import torch
import torch.nn as nn
import numpy as np
import math
import matplotlib.pyplot as plt

device = torch.device("cpu")

# --- Helper Functions ---
def teacher_force_(z, x, alpha, n_obs):
    z[:, :n_obs].mul_(1.0 - alpha).add_(alpha * x)
    return z

def predict_sequence_using_gtf(model, x, alpha, n_interleave):
    b, T, dx = x.shape
    device = x.device
    Z = torch.empty((b, T, model.M), device=device)
    z = x[:, 0, :] @ model.B
    teacher_force_(z, x[:, 0, :], 1.0, model.N)
    for t in range(T):
        if t > 0 and (t % n_interleave == 0):
            teacher_force_(z, x[:, t, :], alpha, model.N)
        z = model(z)
        Z[:, t, :] = z
    return Z

def train_fast(model, dataset, optimizer, scheduler, loss_fn, num_epochs, alpha, n_interleave, batches_per_epoch=20, device="cpu"):
    model.to(device)
    model.train()
    losses = []
    for epoch in range(num_epochs):
        epoch_loss = 0.0
        for _ in range(batches_per_epoch):
            optimizer.zero_grad(set_to_none=True)
            x, y, s = dataset.sample_batch()
            x, y = x.to(device), y.to(device)
            z_hat = predict_sequence_using_gtf(model, x, alpha, n_interleave)
            loss = loss_fn(z_hat[:, :, :model.N], y)
            loss.backward()
            optimizer.step()
            epoch_loss += loss.item()
        scheduler.step()
        epoch_loss /= batches_per_epoch
        losses.append(epoch_loss)
        if epoch % 100 == 0: print(f"Epoch {epoch} | Loss: {epoch_loss:.6f}")
    return losses, []

# --- Model Definitions ---
class AL_RNN_Original(nn.Module):
    def __init__(self, M, P, N):
        super().__init__()
        self.M, self.P, self.N = M, P, N
        self.A = nn.Parameter(self._init_A())
        self.W = nn.Parameter(torch.randn(M, M) * 0.01)
        self.h = nn.Parameter(torch.zeros(M))
        self.B = nn.Parameter(self._init_uniform((N, M)))
    def _init_A(self):
        R = np.random.randn(self.M, self.M).astype(np.float32)
        K = (R.T @ R) / self.M + np.eye(self.M, dtype=np.float32)
        return torch.from_numpy(np.diag(K / np.max(np.abs(np.linalg.eigvals(K)))).astype(np.float32))
    def _init_uniform(self, shape):
        r = 1.0 / math.sqrt(shape[0])
        return nn.init.uniform_(torch.empty(*shape), -r, r)
    def forward(self, z):
        z_relu = z.clone()
        z_relu[:, -self.P:] = F.relu(z_relu[:, -self.P:])
        return self.A * z + z_relu @ self.W.t() + self.h

class AL_RNN_Orthogonal(nn.Module):
    def __init__(self, M, P, N):
        super().__init__()
        self.M, self.P, self.N = M, P, N
        self.A = nn.Parameter(self._init_A())
        self.W = nn.Parameter(torch.randn(M, M) * 0.01)
        self.h = nn.Parameter(torch.zeros(M))
        self.B = nn.Parameter(self._init_uniform((N, M)))
        self.transform = nn.Linear(M, M)
        torch.nn.utils.parametrizations.orthogonal(self.transform)
    def _init_A(self):
        R = np.random.randn(self.M, self.M).astype(np.float32)
        K = (R.T @ R) / self.M + np.eye(self.M, dtype=np.float32)
        return torch.from_numpy(np.diag(K / np.max(np.abs(np.linalg.eigvals(K)))).astype(np.float32))
    def _init_uniform(self, shape):
        r = 1.0 / math.sqrt(shape[0])
        return nn.init.uniform_(torch.empty(*shape), -r, r)
    def forward(self, z):
        z_trans = self.transform(z)
        z_relu = z_trans.clone()
        z_relu[:, -self.P:] = F.relu(z_relu[:, -self.P:])
        return self.A * z + z_relu @ self.W.t() + self.h

# --- Execution ---
print("Generating Rotated & Translated Lorenz Dataset...")
Q_dataset = random_orthogonal_matrix(N, seed=42)
translation_vector = np.random.randn(N).astype(np.float32) * 0.0
X_train_trans = apply_rotation(X_train, Q_dataset) + translation_vector
X_test_trans = apply_rotation(X_test, Q_dataset) + translation_vector

def train_model_on_data(model_class, data, M=20, P=2, num_epochs=600, device="cpu"):
    dataset = TimeSeriesDataset(data, sequence_length=128, batch_size=32)
    model = model_class(M=M, P=P, N=data.shape[-1]).to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)
    scheduler = torch.optim.lr_scheduler.ExponentialLR(optimizer, gamma=np.exp(np.log(1e-5/1e-3)/num_epochs))
    losses, _ = train_fast(model, dataset, optimizer, scheduler, nn.MSELoss(), num_epochs, 1.0, 16, 20, device)
    return model, losses

print("\n--- Training Original AL_RNN ---")
model_orig, losses_orig = train_model_on_data(AL_RNN_Original, X_train_trans, num_epochs=800, device=device)
print("\n--- Training Orthogonal AL_RNN ---")
model_ortho, losses_ortho = train_model_on_data(AL_RNN_Orthogonal, X_train_trans, num_epochs=800, device=device)

plt.figure(figsize=(8, 4))
plt.plot(losses_orig, label="Original")
plt.plot(losses_ortho, label="Orthogonal")
plt.yscale("log"); plt.legend(); plt.show()

import matplotlib.pyplot as plt
import torch
from matplotlib import cm

# --- Required Helper Functions ---
@torch.inference_mode()
def predict_free_sequence(model, x0, T):
    # x0: (batch, N)
    b, N = x0.shape
    device = x0.device
    Z = torch.empty((b, T, model.M), device=device)
    z = x0 @ model.B
    z[:, :N] = x0
    for t in range(T):
        z = model(z)
        Z[:, t, :] = z
    return Z

@torch.inference_mode()
def generate_orbit(model, x0, T_gen, T_r=0, device="cpu"):
    x0_t = torch.tensor(x0[None, :], dtype=torch.float32, device=device)
    # predict_free_sequence is expected to be defined
    orbit = predict_free_sequence(model, x0_t, T_gen + T_r).cpu().numpy()[0]
    if T_r > 0:
        orbit = orbit[T_r:]
    return orbit

# 1. Generate the orbits first to ensure variables exist
T_gen = 5000
# We use the trained models from the previous step to generate free-run orbits
with torch.no_grad():
    orbit_orig = generate_orbit(model_orig, X_test_trans[0], T_gen=T_gen, device=device)
    orbit_ortho = generate_orbit(model_ortho, X_test_trans[0], T_gen=T_gen, device=device)

def plot_three_way_comparison(X_true, orbit_orig, orbit_ortho, num_steps=5000, title="Lorenz Attractor Reconstruction Comparison"):
    """
    Plots the Ground Truth, Original Model generation, and Orthogonal Model generation side-by-side.
    """
    fig = plt.figure(figsize=(18, 6))

    # --- Panel 1: Ground Truth ---
    ax1 = fig.add_subplot(131, projection='3d')
    ax1.plot(
        X_true[:num_steps, 0], X_true[:num_steps, 1], X_true[:num_steps, 2],
        color='black', alpha=0.7, linewidth=0.6
    )
    ax1.set_title("Ground Truth\n(Rotated & Translated)")
    ax1.axis("off")

    # --- Panel 2: Original AL_RNN ---
    ax2 = fig.add_subplot(132, projection='3d')
    ax2.plot(
        orbit_orig[:num_steps, 0], orbit_orig[:num_steps, 1], orbit_orig[:num_steps, 2],
        color='red', alpha=0.7, linewidth=0.6
    )
    ax2.set_title("Original AL_RNN\n(Standard Linear)")
    ax2.axis("off")

    # --- Panel 3: Orthogonal AL_RNN ---
    ax3 = fig.add_subplot(133, projection='3d')
    ax3.plot(
        orbit_ortho[:num_steps, 0], orbit_ortho[:num_steps, 1], orbit_ortho[:num_steps, 2],
        color='blue', alpha=0.7, linewidth=0.6
    )
    ax3.set_title("Orthogonal AL_RNN\n(O(n) + Translation)")
    ax3.axis("off")

    fig.suptitle(title, fontsize=16, fontweight='bold')
    plt.tight_layout()
    plt.show()

# 2. Execute the Plot
plot_three_way_comparison(
    X_true=X_test_trans,
    orbit_orig=orbit_orig,
    orbit_ortho=orbit_ortho,
    num_steps=T_gen,
    title="Model Performance on Rotated Lorenz Dataset"
)